import { Router } from "express";
import { requireAuth } from "../middlewares/auth.middleware.js";
import { asyncHandler } from "../utils/asyncHandler.js";
import { aiService } from "../ai/ai.service.js";
import { generateApplicationKit } from "../services/application-kit.service.js";
import { tailorResumeForJob } from "../services/resume-tailor.service.js";
import { matchJob } from "../services/job-match.service.js";
import { analyzeResume } from "../services/resume-analysis.service.js";
import { generateSkillGap } from "../services/skill-gap.service.js";
import { checkJobScam } from "../services/scam-detector.service.js";
import { chatWithMentor } from "../services/career-chat.service.js";
import { generatePortfolio } from "../services/portfolio.service.js";
import { generateFollowUpMessage } from "../services/followup.service.js";

const router = Router();
router.use(requireAuth);
router.post("/analyze-resume", asyncHandler(async (req, res) => res.json({ success: true, data: await analyzeResume(req.user!.id, req.body.resumeId, req.body.targetRole) })));
router.post("/match-job", asyncHandler(async (req, res) => res.json({ success: true, data: await matchJob(req.user!.id, req.body.jobId, req.body.resumeId) })));
router.post("/tailor-resume", asyncHandler(async (req, res) => res.json({ success: true, data: await tailorResumeForJob(req.user!.id, req.body.jobId, req.body.baseResumeId) })));
router.post("/generate-application-kit", asyncHandler(async (req, res) => res.json({ success: true, data: await generateApplicationKit(req.user!.id, req.body) })));
router.post("/cover-letter", asyncHandler(async (req, res) => res.json({ success: true, data: await aiService.coverLetter(req.user!.id, req.body) })));
router.post("/interview-prep", asyncHandler(async (req, res) => res.json({ success: true, data: await aiService.interviewPrep(req.user!.id, req.body) })));
router.post("/mock-interview", asyncHandler(async (req, res) => res.json({ success: true, data: await aiService.mockInterview(req.user!.id, req.body) })));
router.post("/skill-gap", asyncHandler(async (req, res) => res.json({ success: true, data: await generateSkillGap(req.user!.id, req.body) })));
router.post("/scam-check", asyncHandler(async (req, res) => res.json({ success: true, data: await checkJobScam(req.user!.id, req.body) })));
router.post("/chat", asyncHandler(async (req, res) => res.json({ success: true, data: await chatWithMentor(req.user!.id, req.body) })));
router.post("/rejection-analysis", asyncHandler(async (req, res) => res.json({ success: true, data: await aiService.rejectionAnalysis(req.user!.id, req.body) })));
router.post("/linkedin-optimizer", asyncHandler(async (req, res) => res.json({ success: true, data: await aiService.linkedinOptimizer(req.user!.id, req.body) })));
router.post("/portfolio-generator", asyncHandler(async (req, res) => res.json({ success: true, data: await generatePortfolio(req.user!.id, req.body) })));
router.post("/follow-up-message", asyncHandler(async (req, res) => res.json({ success: true, data: await generateFollowUpMessage(req.user!.id, req.body) })));
export default router;
