import { Router } from "express";
import { requireAuth } from "../middlewares/auth.middleware.js";
import { enforceAiCreditLimit } from "../middlewares/usage-limit.middleware.js";
import { validateBody } from "../middlewares/validate.js";
import { asyncHandler } from "../utils/asyncHandler.js";
import { aiService } from "../ai/ai.service.js";
import { generateApplicationKit } from "../services/application-kit.service.js";
import { tailorResumeForJob } from "../services/resume-tailor.service.js";
import { matchJob } from "../services/job-match.service.js";
import { analyzeResume } from "../services/resume-analysis.service.js";
import { generateSkillGap, listLearningPlans, updateLearningPlan } from "../services/skill-gap.service.js";
import { checkJobScam } from "../services/scam-detector.service.js";
import { chatWithMentor } from "../services/career-chat.service.js";
import { generatePortfolio } from "../services/portfolio.service.js";
import { generateFollowUpMessage } from "../services/followup.service.js";
import { checkGitHubProof } from "../services/github-proof.service.js";
import { aiContextSchema } from "../validators/ai.validator.js";

const router = Router();
router.use(requireAuth);
router.get("/status", asyncHandler(async (_req, res) => res.json({ success: true, data: aiService.status() })));
router.get("/usage", asyncHandler(async (req, res) => res.json({ success: true, data: await aiService.usage(req.user!.id) })));
router.post("/analyze-resume", enforceAiCreditLimit("resume-analysis"), validateBody(aiContextSchema), asyncHandler(async (req, res) => res.json({ success: true, data: await analyzeResume(req.user!.id, req.body.resumeId, req.body.targetRole) })));
router.post("/match-job", enforceAiCreditLimit("job-match"), validateBody(aiContextSchema), asyncHandler(async (req, res) => res.json({ success: true, data: await matchJob(req.user!.id, req.body.jobId, req.body.resumeId) })));
router.post("/tailor-resume", enforceAiCreditLimit("tailor-resume"), validateBody(aiContextSchema), asyncHandler(async (req, res) => res.json({ success: true, data: await tailorResumeForJob(req.user!.id, req.body.jobId, req.body.baseResumeId) })));
router.post("/generate-application-kit", enforceAiCreditLimit("application-kit"), validateBody(aiContextSchema), asyncHandler(async (req, res) => res.json({ success: true, data: await generateApplicationKit(req.user!.id, req.body) })));
router.post("/cover-letter", enforceAiCreditLimit("cover-letter"), validateBody(aiContextSchema), asyncHandler(async (req, res) => res.json({ success: true, data: await aiService.coverLetter(req.user!.id, req.body) })));
router.post("/interview-prep", enforceAiCreditLimit("interview-prep"), validateBody(aiContextSchema), asyncHandler(async (req, res) => res.json({ success: true, data: await aiService.interviewPrep(req.user!.id, req.body) })));
router.post("/mock-interview", enforceAiCreditLimit("mock-interview"), validateBody(aiContextSchema), asyncHandler(async (req, res) => res.json({ success: true, data: await aiService.mockInterview(req.user!.id, req.body) })));
router.get("/skill-gap/plans", asyncHandler(async (req, res) => res.json({ success: true, data: await listLearningPlans(req.user!.id) })));
router.patch("/skill-gap/plans/:id", asyncHandler(async (req, res) => res.json({ success: true, data: await updateLearningPlan(req.user!.id, req.params.id as string, req.body) })));
router.post("/skill-gap", enforceAiCreditLimit("skill-gap"), validateBody(aiContextSchema), asyncHandler(async (req, res) => res.json({ success: true, data: await generateSkillGap(req.user!.id, req.body) })));
router.post("/scam-check", enforceAiCreditLimit("scam-check"), validateBody(aiContextSchema), asyncHandler(async (req, res) => res.json({ success: true, data: await checkJobScam(req.user!.id, req.body) })));
router.post("/chat", enforceAiCreditLimit("career-chat"), validateBody(aiContextSchema), asyncHandler(async (req, res) => res.json({ success: true, data: await chatWithMentor(req.user!.id, req.body) })));
router.post("/rejection-analysis", enforceAiCreditLimit("rejection-analysis"), validateBody(aiContextSchema), asyncHandler(async (req, res) => res.json({ success: true, data: await aiService.rejectionAnalysis(req.user!.id, req.body) })));
router.post("/linkedin-optimizer", enforceAiCreditLimit("linkedin-optimizer"), validateBody(aiContextSchema), asyncHandler(async (req, res) => res.json({ success: true, data: await aiService.linkedinOptimizer(req.user!.id, req.body) })));
router.post("/portfolio-generator", enforceAiCreditLimit("portfolio-generator"), validateBody(aiContextSchema), asyncHandler(async (req, res) => res.json({ success: true, data: await generatePortfolio(req.user!.id, req.body) })));
router.post("/follow-up-message", enforceAiCreditLimit("follow-up-message"), validateBody(aiContextSchema), asyncHandler(async (req, res) => res.json({ success: true, data: await generateFollowUpMessage(req.user!.id, req.body) })));
router.post("/github-analyzer", enforceAiCreditLimit("github-analyzer"), validateBody(aiContextSchema), asyncHandler(async (req, res) => res.json({ success: true, data: await checkGitHubProof(req.body) })));
export default router;

